/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.Helicopter;
import GUI.Helicopter;
import GUI.Submarine;
import GUI.Submarine;
import GUI.Tank;
import GUI.Tank;
import GUI.controller;
import GUI.controller;
import GUI.mainController;
import GUI.mainController;
import jaco.mp3.player.MP3Player;
import java.awt.event.MouseEvent;
import java.io.File;

/**
 *
 * @author ranga
 */
public class Home extends javax.swing.JFrame {

    private MP3Player bgMusicPlayer;

    /**
     * Creates new form Home
     */
    public Home() {
        File mp3File = new File("C:\\Users\\ranga\\Downloads\\bg_sound.mp3");
        if (mp3File.exists()) {
            System.out.println("File found: " + mp3File.getAbsolutePath());
        } else {
            System.out.println("File not found!");
        }
        bgMusicPlayer = new MP3Player(mp3File);
        bgMusicPlayer.setRepeat(true);
        bgMusicPlayer.play();
        initComponents();

        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGame = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(962, 600));
        getContentPane().setLayout(null);

        startGame.setBackground(new java.awt.Color(51, 51, 51));
        startGame.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        startGame.setForeground(new java.awt.Color(255, 255, 255));
        startGame.setText("Start Game");
        startGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startGameMouseEntered(evt);
            }
        });
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });
        getContentPane().add(startGame);
        startGame.setBounds(0, 160, 140, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Screenshot 2024-12-09 022446.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 250, 130);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Game Settings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 230, 140, 40);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Game Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 300, 140, 40);

        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(842, 520));
        jLabel2.setMinimumSize(new java.awt.Dimension(842, 520));
        jLabel2.setPreferredSize(new java.awt.Dimension(842, 520));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        File mp3File = new File("C:\\Users\\ranga\\Downloads\\gun-shots-from-a-distance-7-96391.mp3");
        if (mp3File.exists()) {
            System.out.println("File found: " + mp3File.getAbsolutePath());
        } else {
            System.out.println("File not found!");
        }
        MP3Player mp3Player = new MP3Player(mp3File);

        mp3Player.play();
        Helicopter heli = new Helicopter();
        Tank warTank = new Tank();
        Submarine sub = new Submarine();
        controller control = new controller(heli, warTank, sub);
        new mainController(control).setVisible(true);

    }//GEN-LAST:event_startGameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void startGameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGameMouseEntered
        // TODO add your handling code here:\


    }//GEN-LAST:event_startGameMouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.out.println("hi");
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
